FROM python:3.7.2

RUN mkdir -p /usr/src/<your-bot-folder>
WORKDIR /usr/src/<your-bot-folder>

COPY requirements.txt /usr/src/<your-bot-folder>
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ /usr/src/<your-bot-folder>

ENTRYPOINT ["python", "<your-bot-script>"]

